#!/usr/bin/env python3
# -*- coding: utf-8 -*-

' 如果手头有一个月的gc日志用于合并 '

__author__ = 'bokai'

import os
import time


def merge_log_files(log_files_path):
    # gclogs/_merged.gc.log
    result_file_name = log_files_path + os.sep + '_merged.gc.log'
    if os.path.exists(result_file_name):
        print('result file already exists: ', result_file_name, '.')
        return
    writer = open(result_file_name, 'a+')
    log_file_start_with = ''
    for parent, dicts, fileNames in os.walk(log_files_path):
        for log_file in fileNames:
            if len(log_file) == 25:
                # fanruan.gc.log.2019-01
                log_file_start_with = parent + os.sep + log_file[:-2]
                break
    date_start_with = 1
    date_start_with_str = '' + str(date_start_with)
    if len(str(date_start_with)) == 1:
        date_start_with_str = '0' + str(date_start_with)
    while os.path.exists(log_file_start_with + date_start_with_str):
        reader = open(log_file_start_with + date_start_with_str)
        # 写一个文件 换一行
        writer.write(reader.read())
        date_start_with_str = '' + str(date_start_with)
        date_start_with += 1
        if len(str(date_start_with)) == 1:
            date_start_with_str = '0' + str(date_start_with)
        else:
            date_start_with_str = str(date_start_with)
    if os.path.exists(log_files_path + 'fanruan.gc.log'):
        reader = open(log_files_path + 'fanruan.gc.log')
        # 写整个文件
        writer.write(reader.read())


if __name__ == '__main__':
    log_file_path = input('该月的gc日志文件夹: ')
    start_time = time.time() / 1000
    merge_log_files(log_file_path)
    end_time = time.time() / 1000
    print('spend ', end_time - start_time, ' ms')
